# Documentation: https://roots.io/trellis/docs/local-development-setup/
# `wordpress_sites` options: https://roots.io/trellis/docs/wordpress-sites
# Define accompanying passwords/secrets in group_vars/development/vault.yml

wordpress_sites:
  galyonj.com:
    site_hosts:
      - canonical: galyonj.test
        redirects:
          - www.galyonj.test
      - canonical: donnoshigherground.test
        redirects:
          - www.donnoshigherground.test
      - canonical: foresthillsjacketregiment.test
        redirects:
          - www.foresthillsjacketregiment.test
      - canonical: chainmaillebykitty.com
        redirects:
          - www.chainmaillebykitty.com
    local_path: ../site # path targeting local Bedrock site directory (relative to Ansible root)
    admin_email: galyon.jb@gmail.com
    admin_user: jgalyon
    env:
      db_prefix: m1rr0rr34p3r_
    multisite:
      enabled: true
      subdomain: false
    ssl:
      enabled: false
      provider: self-signed
    cache:
      enabled: false
