# Documentation: https://roots.io/trellis/docs/remote-server-setup/
# `wordpress_sites` options: https://roots.io/trellis/docs/wordpress-sites
# Define accompanying passwords/secrets in group_vars/production/vault.yml

wordpress_sites:
  galyonj.com:
    site_hosts:
      - canonical: galyonj.com
        redirects:
          - www.galyonj.com
      - canonical: donnoshigherground.com
        redirects:
          - www.donnoshigherground.com
      - canonical: foresthillsjacketregiment.test
        redirects:
          - www.foresthillsjacketregiment.test
      - canonical: chainmaillebykitty.com
        redirects:
          - www.chainmaillebykitty.com
    local_path: ../site # path targeting local Bedrock site directory (relative to Ansible root)
    repo: git@github.com:galyonj/mirror-reaper.git # replace with your Git repo URL
    repo_subtree_path: site # relative path to your Bedrock/WP directory in your repo
    branch: master
    admin_email: galyon.jb@gmail.com
    admin_user: jgalyon
    env:
      db_prefix: m1rr0rr34p3r_
    multisite:
      enabled: true
      subdomain: false
    ssl:
      enabled: true
      provider: letsencrypt
    cache:
      enabled: true
